export enum ObservationType {
    FILE_OPENED = "FILE_OPENED",
    FILE_SAVED = "FILE_SAVED",
    FILE_CREATED = "FILE_CREATED",
    FILE_DELETED = "FILE_DELETED",

    EDITOR_CHANGED = "EDITOR_CHANGED",

    CURSOR_MOVED = "CURSOR_MOVED",

    ERROR_DETECTED = "ERROR_DETECTED",
    WARNING_DETECTED = "WARNING_DETECTED",
    SYNTAX_ERROR = "SYNTAX_ERROR",
    DIAGNOSTIC_BATCH = "DIAGNOSTIC_BATCH",

    DEBUG_STARTED = "DEBUG_STARTED",
    DEBUG_STOPPED = "DEBUG_STOPPED",
    DEBUG_INTERRUPTION = "DEBUG_INTERRUPTION",

    TERMINAL_OPENED = "TERMINAL_OPENED",
    TERMINAL_CLOSED = "TERMINAL_CLOSED",
    RUNTIME_CRASH = "RUNTIME_CRASH",

    GIT_BRANCH_CHANGED = "GIT_BRANCH_CHANGED",
    SUCCESSFUL_CHECKPOINT = "SUCCESSFUL_CHECKPOINT",
    GIT_CONFLICT_DETECTED = "GIT_CONFLICT_DETECTED",

    EXTENSION_INSTALLED = "EXTENSION_INSTALLED",
    EXTENSION_REMOVED = "EXTENSION_REMOVED",

    UNKNOWN = "UNKNOWN"
}
