import * as fs from 'fs';
import * as path from 'path';
import * as vscode from 'vscode';

const DEFAULT_ENV_HEADER = "# Environment variables (auto-generated by BotX)\n";

interface ParsedEnvLine {
    key: string;
    line: string;
}

function findEnvBaseline(root: string): string | null {
    for (const name of [".env.example", ".env.template"]) {
        const candidate = path.join(root, name);
        if (fs.existsSync(candidate)) {
            return candidate;
        }
    }
    return null;
}

function parseEnvLine(line: string): ParsedEnvLine | null {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) {
        return null;
    }
    const eqIdx = trimmed.indexOf("=");
    if (eqIdx === -1) {
        return null;
    }
    const key = trimmed.slice(0, eqIdx).trim();
    if (!key) {
        return null;
    }
    return { key, line };
}

function indexEnvLines(content: string): Map<string, string> {
    const map = new Map<string, string>();
    for (const line of content.split(/\r?\n/)) {
        const parsed = parseEnvLine(line);
        if (parsed) {
            map.set(parsed.key, parsed.line);
        }
    }
    return map;
}

/**
 * Creates or updates `.env` in the first workspace root using `.env.example`
 * (or `.env.template`) as a baseline. Keys already configured in `.env` keep
 * their value; missing keys are filled in with the template's default
 * placeholder. Returns true on success so the caller can reflect the outcome.
 */
export async function setupWorkspaceEnv(): Promise<boolean> {
    const folders = vscode.workspace.workspaceFolders;
    if (!folders || folders.length === 0) {
        vscode.window.showWarningMessage("BotX: No workspace folder open — cannot set up .env.");
        return false;
    }

    const root = folders[0].uri.fsPath;
    const envPath = path.join(root, ".env");
    const baselinePath = findEnvBaseline(root);

    if (!baselinePath) {
        if (!fs.existsSync(envPath)) {
            try {
                fs.writeFileSync(envPath, DEFAULT_ENV_HEADER, "utf-8");
            } catch (err) {
                vscode.window.showErrorMessage(`BotX: Could not create .env: ${String(err)}`);
                return false;
            }
            vscode.window.showInformationMessage("BotX: Created .env file.");
            return true;
        }
        vscode.window.showInformationMessage("BotX: .env already exists and no template was found — nothing to do.");
        return true;
    }

    try {
        const baselineLines = fs.readFileSync(baselinePath, "utf-8").split(/\r?\n/);
        const existingContent = fs.existsSync(envPath) ? fs.readFileSync(envPath, "utf-8") : "";
        const existingLineByKey = indexEnvLines(existingContent);
        const baselineKeys = new Set<string>();
        const missingKeys: string[] = [];

        const outputLines: string[] = [];
        for (const line of baselineLines) {
            const parsed = parseEnvLine(line);
            if (!parsed) {
                outputLines.push(line);
                continue;
            }
            baselineKeys.add(parsed.key);
            const existingLine = existingLineByKey.get(parsed.key);
            if (existingLine !== undefined) {
                outputLines.push(existingLine);
            } else {
                outputLines.push(line);
                missingKeys.push(parsed.key);
            }
        }

        for (const [key, line] of existingLineByKey) {
            if (!baselineKeys.has(key)) {
                outputLines.push(line);
            }
        }

        const result = outputLines.join("\n").replace(/\n+$/, "\n");
        fs.writeFileSync(envPath, result, "utf-8");

        const label = missingKeys.length === 1 ? "key" : "keys";
        vscode.window.showInformationMessage(
            `BotX: .env updated from ${path.basename(baselinePath)} — added ${missingKeys.length} missing ${label}.`
        );
        return true;
    } catch (err) {
        vscode.window.showErrorMessage(`BotX: Could not update .env: ${String(err)}`);
        return false;
    }
}
