export enum BehaviourAction {
    NONE = "NONE",
    SHOW_HINT = "SHOW_HINT",
    SHOW_ERROR_HELP = "SHOW_ERROR_HELP",
    SHOW_WARNING = "SHOW_WARNING",
    SHOW_DOCUMENTATION = "SHOW_DOCUMENTATION",
    SHOW_DEBUG_HELP = "SHOW_DEBUG_HELP",
    SHOW_GIT_HELP = "SHOW_GIT_HELP",
    SHOW_EXTENSION_HELP = "SHOW_EXTENSION_HELP",
    CELEBRATE = "CELEBRATE",
    ASK_USER = "ASK_USER"
}
