export enum ContextType {
    IDLE = "IDLE",
    READING_CODE = "READING_CODE",
    WRITING_CODE = "WRITING_CODE",
    EDITING_JAVA = "EDITING_JAVA",
    EDITING_TYPESCRIPT = "EDITING_TYPESCRIPT",
    EDITING_PYTHON = "EDITING_PYTHON",
    EDITING_CPP = "EDITING_CPP",
    FIXING_COMPILER_ERROR = "FIXING_COMPILER_ERROR",
    DEBUGGING = "DEBUGGING",
    USING_TERMINAL = "USING_TERMINAL",
    WORKING_WITH_GIT = "WORKING_WITH_GIT",
    MANAGING_EXTENSIONS = "MANAGING_EXTENSIONS",
    SWITCHING_FILES = "SWITCHING_FILES",
    USER_STUCK_ON_ERROR = "USER_STUCK_ON_ERROR",
    UNKNOWN = "UNKNOWN"
}
