export enum EventType {
    EDITOR_ACTIVE = "EDITOR_ACTIVE",
    EDITOR_SWITCHED = "EDITOR_SWITCHED",
    EDITOR_OPENED = "EDITOR_OPENED",

    CURSOR_MOVED = "CURSOR_MOVED",

    FILE_CREATED = "FILE_CREATED",
    FILE_DELETED = "FILE_DELETED",
    FILE_RENAMED = "FILE_RENAMED",
    FILE_SAVED = "FILE_SAVED",

    DIAGNOSTICS_UPDATED = "DIAGNOSTICS_UPDATED",

    TERMINAL_OPENED = "TERMINAL_OPENED",
    TERMINAL_CLOSED = "TERMINAL_CLOSED",
    TERMINAL_ACTIVE = "TERMINAL_ACTIVE",
    TERMINAL_COMMAND_FAILED = "TERMINAL_COMMAND_FAILED",

    DEBUG_STARTED = "DEBUG_STARTED",
    DEBUG_STOPPED = "DEBUG_STOPPED",
    DEBUG_BREAKPOINT_HIT = "DEBUG_BREAKPOINT_HIT",

    GIT_BRANCH_CHANGED = "GIT_BRANCH_CHANGED",
    GIT_REPOSITORY_CHANGED = "GIT_REPOSITORY_CHANGED",
    GIT_COMMIT_SUCCESS = "GIT_COMMIT_SUCCESS",
    GIT_CONFLICT_DETECTED = "GIT_CONFLICT_DETECTED",
    GIT_CONFLICT_RESOLVED = "GIT_CONFLICT_RESOLVED",

    EXTENSION_INSTALLED = "EXTENSION_INSTALLED",
    EXTENSION_UNINSTALLED = "EXTENSION_UNINSTALLED",
    EXTENSION_ENABLED = "EXTENSION_ENABLED",
    EXTENSION_DISABLED = "EXTENSION_DISABLED",

    STUCK_RAPID_SAVE = "STUCK_RAPID_SAVE",
    STUCK_IDLE_FOCUS = "STUCK_IDLE_FOCUS",

    ENVIRONMENT_CHECK = "ENVIRONMENT_CHECK",

    DEPRECATED_API_DETECTED = "DEPRECATED_API_DETECTED"
}
