export enum DecisionType {
    DO_NOTHING = "DO_NOTHING",
    SHOW_HINT = "SHOW_HINT",
    SHOW_WARNING = "SHOW_WARNING",
    SHOW_ERROR_HELP = "SHOW_ERROR_HELP",
    SUGGEST_DOCUMENTATION = "SUGGEST_DOCUMENTATION",
    SUGGEST_DEBUGGING = "SUGGEST_DEBUGGING",
    SUGGEST_GIT_ACTION = "SUGGEST_GIT_ACTION",
    SUGGEST_EXTENSION = "SUGGEST_EXTENSION",
    CONGRATULATE = "CONGRATULATE",
    ASK_USER = "ASK_USER",
    WAIT = "WAIT",
    UNKNOWN = "UNKNOWN"
}
